# Generated by Django 4.2 on 2023-04-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_rename_img_movie_imgs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imgs',
            new_name='img',
        ),
    ]
