# Generated by Django 4.2 on 2023-04-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_rename_imgs_movie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='img',
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='aswani', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
